apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-default-builder-service-account
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-6"
secrets:
  - name: registry-credentials
imagePullSecrets:
  - name: registry-credentials
