apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-controller-admin-binding
subjects:
- kind: ServiceAccount
  name: kpack-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kpack-controller-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-controller-servicebindings-binding
subjects:
- kind: ServiceAccount
  name: kpack-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kpack-controller-servicebindings-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-webhook-certs-mutatingwebhookconfiguration-admin-binding
subjects:
- kind: ServiceAccount
  name: kpack-webhook
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kpack-webhook-mutatingwebhookconfiguration-admin
  apiGroup: rbac.authorization.k8s.io
