apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "rfc3339nano",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
data:
  image: gcr.io/cf-build-service-public/kpack/build-init@sha256:189b8a9cf31950615e1c7e4516f99c69c128ffbd4264b3c2c435d5aca86de26e
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
data:
  image: gcr.io/cf-build-service-public/kpack/build-init-windows@sha256:c5c3beace3a10ad1119a8c031f98d6afb89a727211bc3a75bb565171e947d69d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
data:
  image: gcr.io/cf-build-service-public/kpack/build-waiter@sha256:d770e1c782a827c7532a29036fe73840b4301addf81aad5d2312d45d2a3d2175
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
data:
  image: gcr.io/cf-build-service-public/kpack/rebase@sha256:5ca8b58d10eeb58d5796a9f2a69814cd1a34838da5115c25d9ca2263b9d32c7f
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
data:
  image: gcr.io/cf-build-service-public/kpack/lifecycle@sha256:35b5e30b71461448990ef739d8b6429d050c1e6f0693a5fe292f981365bb13f2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
data:
  image: gcr.io/cf-build-service-public/kpack/completion@sha256:94bc8f1f05c511e75c5a55f67f57712772541c200a65d1b3e539b8f60ae56777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
data:
  image: gcr.io/cf-build-service-public/kpack/completion-windows@sha256:5ef19c84b032813cf525ac31a598cf1e07880cbbe3604b585df1d01ed204b8ec
