apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "rfc3339nano",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init@sha256:7fc4d60e31273189a9655ff8105c02f54f1f0386b819796c97e559bc662ade09
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init-windows@sha256:c0f52c6b6e7f255d8f54674d39d87f8b8acdf760316a313e1de5145e99dd282d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-waiter@sha256:29c17c2ea07f3b3827a389470a289cb3a42545e9945ba2e886291ad6af8f1d18
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
data:
  image: ghcr.io/amphitheatre-app/kpack/rebase@sha256:d31cf2275fbf4fc38198a2b88e7f190308cede8777abf1f58fbcdda4e38e40cb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
data:
  image: ghcr.io/amphitheatre-app/kpack/lifecycle@sha256:199043ac6fd40f772decb804ca92cdcbb22b76cf8db622761e25c39c2925d3b7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion@sha256:4b2abef544f6507727a730e8d3b750f7aa7ed47c7642c521a9987b9b6648198c
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion-windows@sha256:060e691aad66587ad9a87caf448d026719bfbacbf25f3baef1a6111a26c0eeb3
