apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "rfc3339nano",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init@sha256:926aa34112c62ca6c49d8370fb4cfdfaea7d47ed8a3c3e254655526a4a081158
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init-windows@sha256:e9adb6ba4d57e9929fae7f2709a7d1061bd37139139949333d457d7d72907ee4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-waiter@sha256:165eba3b0c508fd61c6ebd0bdd4f51184d2b97e43bbeb45facb6b3caa752ba48
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
data:
  image: ghcr.io/amphitheatre-app/kpack/rebase@sha256:c10b53d6e77f65fe75dae702c074655b3977e5a73db14fcd233b4a6469d8e670
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
data:
  image: ghcr.io/amphitheatre-app/kpack/lifecycle@sha256:199043ac6fd40f772decb804ca92cdcbb22b76cf8db622761e25c39c2925d3b7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion@sha256:0b96c1997a463c7f0cc35246f126a39d7698310d689965cdd6b866dd64064ed5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion-windows@sha256:e0abe02a98cb77f3d3e22ea17ed88c7ae682c62cd0f711fde4b0e1322b460f38
