apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "rfc3339nano",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init@sha256:456781fb9bf5e4b15959dcc2a1afbcb6e89f3ad0ab416f973e24489864088e30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init-windows@sha256:e279a3b19646fa42a54bd42653fa294aac788b6e1d669c470521cc907a8e70e0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-waiter@sha256:223f1402a1305448f6c8cb51970d4f193f363f06ed7876abc0f9b4504c12faa0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
data:
  image: ghcr.io/amphitheatre-app/kpack/rebase@sha256:c592deaf305d5c7710e50702dd413cffa652ee44862ba87c7b752f2b8b9a6472
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
data:
  image: ghcr.io/amphitheatre-app/kpack/lifecycle@sha256:199043ac6fd40f772decb804ca92cdcbb22b76cf8db622761e25c39c2925d3b7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion@sha256:54fcbdbcb45c999ec304cc2a2760e08554640826b0309d13b04ac98dfbf37055
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion-windows@sha256:c0a78fad840730bfb5c1236f88294cb4aa0628dd66c32e13bd3df99da0553ea2
