apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "rfc3339nano",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init@sha256:1f4a1c6a74d9d77565199dda45a252b1f6f3c81eb4d548cc8686005a2a125dff
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init-windows@sha256:ef478d79a5cb84523117a5fb48a20df61b60faf0f26f2dceb61d404a2137ddd6
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-waiter@sha256:111a7b1d3d93a8543bbd702fd72a30a5923487bdaede45f14e357bc9da05cd03
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
data:
  image: ghcr.io/amphitheatre-app/kpack/rebase@sha256:48113871840ced895957372cd8f1a63adf515f07e6bbcfca0478c8922e7b70f1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
data:
  image: ghcr.io/amphitheatre-app/kpack/lifecycle@sha256:199043ac6fd40f772decb804ca92cdcbb22b76cf8db622761e25c39c2925d3b7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion@sha256:856aa75770cefee1f7344f4fde62e54ce842cf7b97d5b0f27fb5ab7b8a5e71b2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion-windows@sha256:003143af4f33ab6a881688ef55a0d3184f17597b17baa602d9d6dfbda01306a5
