apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "rfc3339nano",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init@sha256:78937dfcd61aa44da0c2425c6a1357c05142614758538a9643a2b2ec04362b95
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-init-windows@sha256:8ab4d103f61708ee7c5a14f2d2cf948fe63edf1e5d7f76e13e345188b4325f85
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
data:
  image: ghcr.io/amphitheatre-app/kpack/build-waiter@sha256:06b5956c9c063f455b941d17da77d3d7e137845cbacdf33cf1fdbfa16be62799
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
data:
  image: ghcr.io/amphitheatre-app/kpack/rebase@sha256:95c3b80119e188e56811a3f53373b587b0c90f5980ae5a8f2ce38ca05e6a3837
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
data:
  image: ghcr.io/amphitheatre-app/kpack/lifecycle@sha256:199043ac6fd40f772decb804ca92cdcbb22b76cf8db622761e25c39c2925d3b7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion@sha256:093a2fa6aecb75f38d967a49f3b761eccf98736c8bfc4397dd1dcc5a71c6e2ce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
data:
  image: ghcr.io/amphitheatre-app/kpack/completion-windows@sha256:913526ac02cc7953736f7c3ad901e96dbf081ce3d6cc142522523b4cd923c977
