apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: 0.13.4
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: kpack-control-plane
      serviceAccountName: kpack-controller
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: controller
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        image: ghcr.io/amphitheatre-app/kpack/controller@sha256:6b4c82eec84dbca7930c5a1ece5f3c37a8c9b72d3f3bbf17c3e198ba81f6f7a7
        env:
        - name: ENABLE_PRIORITY_CLASSES
          value: "false"
        - name: INJECTED_SIDECAR_SUPPORT
          value: "false"
        - name: EXPERIMENTAL_GENERATE_SLSA_ATTESTATION
          value: "false"
        - name: INSECURE_SSH_TRUST_UNKNOWN_HOSTS
          value: "true"
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SYSTEM_SERVICE_ACCOUNT
          value: kpack-controller
        - name: BUILD_INIT_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-image
              key: image
        - name: BUILD_INIT_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-windows-image
              key: image
        - name: BUILD_WAITER_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-waiter-image
              key: image
        - name: REBASE_IMAGE
          valueFrom:
            configMapKeyRef:
              name: rebase-image
              key: image
        - name: COMPLETION_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-image
              key: image
        - name: COMPLETION_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-windows-image
              key: image
        resources:
          requests:
            cpu: 20m
            memory: 1Gi
          limits:
            memory: 1Gi
