apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-controller-local-config-binding
subjects:
- kind: ServiceAccount
  name: kpack-controller
roleRef:
  kind: Role
  name: kpack-controller-local-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-webhook-certs-admin-binding
subjects:
- kind: ServiceAccount
  name: kpack-webhook
roleRef:
  kind: Role
  name: kpack-webhook-certs-admin
  apiGroup: rbac.authorization.k8s.io
