apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.kpack.io
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: {{ .Release.Namespace }}
  failurePolicy: Fail
  matchPolicy: Exact
  sideEffects: None
  name: validation.webhook.kpack.io
