apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-webhook
  template:
    metadata:
      labels:
        app: kpack-webhook
        role: kpack-webhook
        version: 0.13.3
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: kpack-control-plane
      serviceAccountName: kpack-webhook
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: webhook
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        image: ghcr.io/amphitheatre-app/kpack/webhook@sha256:aec49b5dd6e3616fcf2d41351a573a544835873f3e997a8c8cc563d22e8a7528
        ports:
        - name: https-webhook
          containerPort: 8443
        env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
