# Default values for amphitheatre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global parameters
# registry: registry.amphitheatre.app

## Amphitheatre CRDs Parameters
crds:
  # Switch to install or uninstall the amphitheatre-crds helm chart
  install: true

# ## Cert Manager Parameters
# cert-manager:
#   # Switch to enable or disable the cert-manager helm chart
#   enabled: false
#   installCRDs: true
#   # podDnsPolicy: "Default"
#   # podDnsConfig:
#   #   nameservers:
#   #     - "1.1.1.1"
#   #     - "8.8.8.8"

# ## Harbor Parameters
# harbor:
#   # # Switch to enable or disable the harbor helm chart
#   # enabled: true
#   # # String to fully override common.names.fullname template with a string
#   # fullnameOverride: harbor
#   # # The initial password of Harbor admin.
#   # adminPassword: "Harbor12345"

#   # # # The external URL for Harbor Core service
#   # externalURL: https://registry.amphitheatre.app
#   # # The way to expose Harbor. Allowed values are [ ingress | proxy ]
#   # # Use "proxy" to use a deploy NGINX proxy in front of Harbor services
#   # exposureType: proxy
#   # # Service parameters
#   # service:
#   #   # NGINX proxy service type
#   #   type: ClusterIP
#   #   # Additional custom annotations for NGINX proxy service
#   #   annotations:
#   #     # cert-manager.io/cluster-issuer: lets-encrypt-cluster-issuer
#   #     # cert-manager.io/issue-temporary-certificate: "true"
#   #     # acme.cert-manager.io/http01-edit-in-place: "true"
#   # # NGINX Parameters
#   # nginx:
#   #   # TLS parameters
#   #   tls:
#   #     # Enable TLS termination
#   #     enabled: true
#   #     # existingSecret: harbor-nginx-proxy-certificate
#   #     # The common name used to generate the self-signed TLS certificates
#   #     commonName: registry.amphitheatre.app

#   # # # The external URL for Harbor Core service
#   # externalURL: https://registry.amphitheatre.app
#   # # The way to expose Harbor. Allowed values are [ ingress | proxy ]
#   # # Use "ingress" to use an Ingress Controller as proxy
#   # exposureType: ingress
#   # # Ingress parameters
#   # ingress:
#   #   # Configure the ingress resource that allows you to access Harbor Core
#   #   core:
#   #     # Default host for the ingress record
#   #     hostname: registry.amphitheatre.app
#   #     # Additional annotations for the Ingress resource
#   #     annotations:
#   #       kubernetes.io/ingress.class: nginx
#   #       ingress.kubernetes.io/ssl-redirect: 'true'
#   #       ingress.kubernetes.io/proxy-body-size: '0'
#   #       nginx.ingress.kubernetes.io/ssl-redirect: 'true'
#   #       nginx.ingress.kubernetes.io/proxy-body-size: '0'
#   #       cert-manager.io/cluster-issuer: lets-encrypt-cluster-issuer
#   #       # cert-manager.io/issue-temporary-certificate: "true"
#   #       # acme.cert-manager.io/http01-edit-in-place: "true"
#   #     tls: true

## Kpack Parameters
kpack:
  # Switch to enable or disable the kpack helm chart
  enabled: true

# ## Ingress Nginx Parameters
# ingress-nginx:
#   # Switch to enable or disable the ingress-nginx helm chart
#   enabled: false
#   controller:
#     kind: DaemonSet
#     service:
#       enableHttps: true
