# Default values for amphitheatre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: registry.amphitheatre.app

crds:
  enabled: true

cert-manager:
  enabled: true
  installCRDs: true
  podDnsPolicy: "Default"
  # podDnsConfig:
  #   nameservers:
  #     - "1.1.1.1"
  #     - "8.8.8.8"

harbor:
  enabled: true
  fullnameOverride: harbor
  adminPassword: "Harbor12345"

  # externalURL: harbor.amp-system.svc.cluster.local
  # exposureType: proxy
  # service:
  #   type: ClusterIP
  # nginx:
  #   tls:
  #     enabled: false

  externalURL: registry.amphitheatre.app
  exposureType: ingress
  ingress:
    core:
      hostname: registry.amphitheatre.app
      annotations:
        ingress.kubernetes.io/ssl-redirect: 'true'
        ingress.kubernetes.io/proxy-body-size: '0'
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: lets-encrypt-cluster-issuer
        cert-manager.io/issue-temporary-certificate: "true"
        acme.cert-manager.io/http01-edit-in-place: "true"
      tls: true

kpack:
  enabled: true

ingress-nginx:
  enabled: true
  controller:
    kind: DaemonSet
    service:
      enableHttps: true
