## @section Amphitheatre APIServer paramters
apiserver:
  registry: ghcr.io
  repository: amphitheatre-app/amp-apiserver
  tag: v23-04-09-01
  digest: ""

  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  pullSecrets: []

  ## @param replicaCount Number of WordPress replicas to deploy
  replicaCount: 1

  ## Enable debug mode
  debug: false

## @section Database paramters

## MySQL chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/mysql/values.yaml
mysql:
  ## @param mysql.enabled Deploy a MySQL server to satisfy the application database requirement
  ## To use an external database set this to false and configure the `externalDatabase.*` parameters
  enabled: true

  ## @param mysql.auth.rootPassword MySQL root password
  ## @param mysql.auth.database MySQL custom database
  ## @param mysql.auth.username MySQL custom user name
  ## @param mysql.auth.password MySQL custom user password
  auth:
    rootPassword: ""
    database: amphitheatre
    username: amphitheatre
    password: ""

## External Database configuration
## All of these values are only used if `mysql.enabled=false`
externalDatabase:
  ## @param externalDatabase.host External Database server host
  host: localhost

  ## @param externalDatabase.port External Database server port
  port: 3306

  ## @param externalDatabase.username External Database username
  username: amphitheatre

  ## @param externalDatabase.password External Database database password
  password: ""

  ## @param externalDatabase.database ExternalDatabase database name
  database: amphitheatre

## @section Amphitheatre Controllers paramters
controllers:
  registry: ghcr.io
  repository: amphitheatre-app/amp-controllers
  tag: v23-04-09-01
  digest: ""

  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  pullSecrets: []

  ## @param replicaCount Number of WordPress replicas to deploy
  replicaCount: 1

  ## Enable debug mode
  debug: false

## @section Amphitheatre CRDs Parameters
crds:
  # Switch to install or uninstall the amphitheatre-crds helm chart
  install: true

## @section Kpack Parameters
kpack:
  # Switch to enable or disable the kpack helm chart
  enabled: true
