# Default values for amphitheatre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: harbor.amp-system.svc.cluster.local

harbor:
  enabled: true
  fullnameOverride: harbor
  adminPassword: "Harbor12345"
  externalURL: harbor.amp-system.svc.cluster.local
  exposureType: proxy
  service:
    type: ClusterIP
  nginx:
    tls:
      enabled: false

kpack:
  enabled: true
