# Default values for amphitheatre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: ttl.sh

harbor:
  enabled: false

vcluster:
  enabled: false

mysql:
  enabled: false

kpack:
  enabled: true
