{{- if index .Values "cert-manager" "enabled" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-cluster-issuer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  acme:
    # The ACME server URL
    #server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: issuer@amphitheatre.app
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: lets-encrypt-cluster-issuer
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
