apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amphitheatre.controllers.fullname" . }}
  labels:
    {{- include "amphitheatre.controllers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.controllers.autoscaling.enabled }}
  replicas: {{ .Values.controllers.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "amphitheatre.controllers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controllers.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "amphitheatre.controllers.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controllers.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "amphitheatre.controllers.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controllers.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "amphitheatre.controllers.name" . }}
          securityContext:
            {{- toYaml .Values.controllers.securityContext | nindent 12 }}
          image: {{ include "amphitheatre.controllers.image" . }}
          imagePullPolicy: {{ .Values.controllers.image.pullPolicy }}
          env:
            - name: AMP_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: AMP_SERVICE_ACCOUNT_NAME
              value: {{ include "amphitheatre.controllers.serviceAccountName" . }}
            {{- if .Values.controllers.debug }}
            - name: RUST_LOG
              value: debug
            {{- end }}
          resources:
            {{- toYaml .Values.controllers.resources | nindent 12 }}
      {{- with .Values.controllers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
