{{- if .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "amphitheatre.controllers.serviceAccountName" . }}
  labels:
    {{- include "amphitheatre.controllers.labels" . | nindent 4 }}
  {{- with .Values.controllers.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
