apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: amp-default-cluster-builder
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
spec:
  tag: {{ .Values.registry }}/amp-default-cluster-builder
  stack:
    name: amp-default-cluster-stack
    kind: ClusterStack
  store:
    name: amp-default-cluster-store
    kind: ClusterStore
  serviceAccountRef:
    name: amp-default-builder-service-account
    namespace: {{ .Release.Namespace }}
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
