apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: amp-default-cluster-builder
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  tag: ttl.sh/amp-default-cluster-builder
  stack:
    name: amp-default-cluster-stack
    kind: ClusterStack
  store:
    name: amp-default-cluster-store
    kind: ClusterStore
  serviceAccountRef:
    name: kpack-service-account
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
