apiVersion: apps/v1
kind: Deployment
metadata:
  name: amp-controllers
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: amp-controllers
spec:
  replicas: {{ .Values.controllers.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: amp-controllers
  template:
    metadata:
      labels:
        app.kubernetes.io/component: amp-controllers
    spec:
      {{- if .Values.controllers.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.controllers.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: amp-controllers
        securityContext:
          runAsNonRoot: true
        image: {{ include "amphitheatre.controllers.image" . }}
        imagePullPolicy: {{ .Values.controllers.pullPolicy }}
