{{- if not .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-db" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  mysql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
