apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-credentials
  annotations:
    kpack.io/docker: https://core.harbor.domain/
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Harbor12345
