{{- if .Values.harbor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    kpack.io/docker: {{ .Values.harbor.externalURL }}
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: {{ .Values.harbor.adminPassword }}
{{- end }}
