apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: amp-apiserver-binding
subjects:
- kind: ServiceAccount
  name: {{ include "amphitheatre.apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: amp-apiserver
  apiGroup: rbac.authorization.k8s.io
