apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amphitheatre.apiserver.fullname" . }}
  labels:
    {{- include "amphitheatre.apiserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiserver.autoscaling.enabled }}
  replicas: {{ .Values.apiserver.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "amphitheatre.apiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "amphitheatre.apiserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.apiserver.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "amphitheatre.apiserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiserver.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "amphitheatre.apiserver.name" . }}
          securityContext:
            {{- toYaml .Values.apiserver.securityContext | nindent 12 }}
          image: {{ include "amphitheatre.apiserver.image" . }}
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          env:
            - name: AMP_DATABASE_HOST
              value: {{ include "amphitheatre.database.host". | quote }}
            - name: AMP_DATABASE_PORT
              value: {{ include "amphitheatre.database.port". | quote }}
            - name: AMP_DATABASE_NAME
              value: {{ include "amphitheatre.database.name". | quote }}
            - name: AMP_DATABASE_USERNAME
              value: {{ include "amphitheatre.database.username". | quote }}
            - name: AMP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "amphitheatre.database.secretName" . }}
                  key: mysql-password
            - name: AMP_PORT
              value: {{ .Values.service.port }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
