{{- if .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "amphitheatre.apiserver.serviceAccountName" . }}
  labels:
    {{- include "amphitheatre.apiserver.labels" . | nindent 4 }}
  {{- with .Values.apiserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
