apiVersion: v1
kind: Service
metadata:
  name: {{ include "amphitheatre.apiserver.fullname" . }}
  labels:
    {{- include "amphitheatre.apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}

  selector:
    {{- include "amphitheatre.apiserver.selectorLabels" . | nindent 4 }}
