apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
  labels:
    app: default-init
data:
  entrypoint.sh: |
    #!/usr/bin/env bash

    set -euo pipefail
    export REGISTRY_FQDN={{ .Values.registry }}
    export FOLDER=/mnt/etc/docker/certs.d/$REGISTRY_FQDN

    echo "Deleting the custom certificate folder and creating it again"
    rm -rf $FOLDER
    mkdir -p $FOLDER

    echo "Copying the custom certificate"
    cp /registry/tls.crt $FOLDER/client.cert
    cp /registry/tls.key $FOLDER/client.key
    cp /registry/ca.crt $FOLDER/ca.crt

    echo "Certificates copied"
    echo $FOLDER/client.cert
    cat $FOLDER/client.cert
