{{- if eq .Values.runtime "containerd" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cert-daemonset
spec:
  selector:
    matchLabels:
      k8s-app: cert-daemonset
  template:
    metadata:
      annotations:
      labels:
        k8s-app: cert-daemonset
    spec:
      initContainers:
      - image: gcr.io/gcp-runtimes/ubuntu_16_0_4
        name: init
        command: ["/scripts/entrypoint.sh"]
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /mnt/etc
          name: etc
        - mountPath: /registry
          name: nginx-tls-secret
          readOnly: true
        - mountPath: /scripts
          name: entrypoint
        - mountPath: /etc/config
          name: containerd-config
          readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
      - hostPath:
          path: /etc
        name: etc
      - name: nginx-tls-secret
        secret:
          secretName: nginx-tls-secret
          defaultMode: 420
      - name: entrypoint
        configMap:
          name: entrypoint
          defaultMode: 0744
          items:
          - key: entrypoint.sh
            path: entrypoint.sh
      - name: containerd-config
        configMap:
          name: entrypoint
          defaultMode: 0744
          items:
          - key: custom_config.toml
            path: custom_config.toml
      containers:
      - image: gcr.io/google-containers/pause:3.2
        name: pause
{{- end }}
